version: '3'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "9956:3000"
    logging:
      driver: json-file
      options:
        max-size: 200k

  telegraf:
    image: library/telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    logging:
      driver: json-file
      options:
        max-size: 200k

  influxdb:
    image: library/influxdb
    container_name: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    logging:
      driver: json-file
      options:
        max-size: 200k
